routes/web.php
<?php

use App\Http\Controllers\FrontSettingController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\SettingController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::post('/register',[HomeController::class,'register'])->name('register');

// Home
Route::get('/', [HomeController::class, 'home'])->name('home');
// Men
Route::get('/men', [HomeController::class, 'men'])->name('new_arrivals');
Route::get('/women', [HomeController::class, 'woMen'])->name('women_arrivals');
Route::get('/accessories', [HomeController::class, 'Accessories'])->name('accessories_arrivals');
Route::get('product/{id}/details', [HomeController::class, 'menDetails'])->name('men.details');
Route::get('page/contact-us', [HomeController::class, 'contactUs'])->name('page.contact-us');
Route::get('page/return-exchange', [HomeController::class, 'returnExchange'])->name('page.return-exchange');
Route::get('page/privacy-policy', [HomeController::class, 'privacyPolicy'])->name('page.privacy-policy');
Route::get('page/return-policy', [HomeController::class, 'returnPolicy'])->name('page.return-policy');
Route::get('page/offer-policy', [HomeController::class, 'offerPolicy'])->name('page.offer-policy');
//Route::get('women/{id}/details',[HomeController::class,'womenDetails'])->name('women.details');
//Route::get('men/details',function (){
//    return view('by_pass.men_details');
//})->name('men_details');


Route::get('/welcome', function () {
    return view('web.welcome');
});
Route::get('/mens', function () {
    return view('web.mens');
})->name('mens');
Route::get('/single', function () {
    return view('web.single');
})->name('single');
Route::get('/contact', function () {
    return view('web.contact');
})->name('contact');

//Route::middleware(['auth:sanctum', 'verified','role:Admin'])->get('/dashboard', function () {
//    return view('dashboard.dashboard');
//})->name('dashboard');

//Route::group(['middleware' => ['auth:sanctum', 'verified','role:Admin']],function (){
    Route::get('dashboard', [HomeController::class, 'dashboard'])->name('dashboard');
//});


Route::group(['middleware' => 'auth'], function () {

    Route::get('mySetting', [HomeController::class, 'mySetting'])->name('mySetting');

});


// settings routes
Route::get('settings', [SettingController::class, 'index'])->name('settings.index');
Route::post('settings', [SettingController::class, 'update'])->name('settings.update');

// front settings
Route::get('setting/home', [FrontSettingController::class, 'home'])->name('front.settings.home');
Route::post('setting/home', [FrontSettingController::class, 'homeUpdate'])->name('front.settings.home.update');
Route::delete('delete-home-slider/{homeImageSlider}', [FrontSettingController::class, 'deleteHomeSlider'])->name('front.settings.deleteHomeSlider');

Route::get('setting/contact-us', [FrontSettingController::class, 'contactUs'])->name('front.settings.contactUs');
Route::post('setting/contact-us',
    [FrontSettingController::class, 'contactUsUpdate'])->name('front.settings.contactUs.update');

// Order
Route::get('orders', [OrderController::class, 'index'])->name('orders.index');
Route::post('placeOrder', [OrderController::class, 'placeOrder'])->name('placeOrder');
Route::get('getOrderDetails', [OrderController::class, 'getOrderDetails'])->name('getOrderDetails');
Route::post('getOrderDetails', [OrderController::class, 'storeOrderDetails'])->name('storeOrderDetails');
Route::post('storeOrderNewAddress', [OrderController::class, 'storeOrderNewAddress'])->name('storeOrderNewAddress');
Route::post('chooseAddress', [OrderController::class, 'chooseAddress'])->name('chooseAddress');
Route::get('removeProductToBag', [OrderController::class, 'removeProductToBag'])->name('removeProductToBag');


Route::resource('categories', App\Http\Controllers\CategoryController::class);
Route::resource('subCategories', App\Http\Controllers\SubCategoryController::class);
Route::get('get-sub-categories',
    [App\Http\Controllers\SubCategoryController::class, 'getSubCategory'])->name('get.sub.categories');
Route::resource('products', App\Http\Controllers\ProductController::class);
Route::post('products/change-is-active',
    [App\Http\Controllers\ProductController::class, 'changeIsActive'])->name('products.change-is-active');
Route::get('productColorDelete',
    [App\Http\Controllers\ProductController::class, 'productColorDelete'])->name('productColorDelete');
Route::get('productColorImageDelete',
    [App\Http\Controllers\ProductController::class, 'productColorImageDelete'])->name('productColorImageDelete');

Route::resource('colors', App\Http\Controllers\ColorController::class);
Route::resource('variants', App\Http\Controllers\VariantController::class);


Route::group(['prefix' => 'crud-gui'], function () {
    Route::get('generator_builder',
        '\Crud\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');

    Route::get('field_template',
        '\Crud\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');

    Route::get('relation_field_template',
        '\Crud\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');

    Route::post('generator_builder/generate',
        '\Crud\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');

    Route::post('generator_builder/rollback',
        '\Crud\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');

    Route::post(
        'generator_builder/generate-from-file',
        '\Crud\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
    )->name('io_generator_builder_generate_from_file');
});

app/Models/Category.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

/**
 * Class Category
 *
 * @package App\Models
 * @version January 3, 2021, 9:37 am UTC
 * @property string $name
 * @property SubCategory $subCategory
 * @property int $id
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read mixed $image
 * @property-read mixed $total_sub_category
 * @property-read \Illuminate\Database\Eloquent\Collection|Media[] $media
 * @property-read int|null $media_count
 * @property-read int|null $sub_category_count
 * @method static \Illuminate\Database\Eloquent\Builder|Category newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Category newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Category query()
 * @method static \Illuminate\Database\Eloquent\Builder|Category whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Category whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Category whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Category whereUpdatedAt($value)
 * @mixin Model
 */
class Category extends Model implements HasMedia
{
    use HasFactory,HasMediaTrait;

    const IMG_PATH = 'categories';

    public $table = 'categories';

    public $fillable = [
        'name'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'name' => 'required|unique:categories,name',
        'image' => 'required',
    ];

    protected $appends = ['image'];
    protected $hidden = ['media'];

    /**
     * @return mixed
     */
    public function getImageAttribute()
    {
        /** @var Media $media */
        $media = $this->getMedia(self::IMG_PATH)->first();
        if (! empty($media)) {
            return $media->getFullUrl();
        }

        return asset('img/logo.png');
    }

    /**
     * @return HasMany
     */
    public function subCategory()
    {
        return $this->hasMany(SubCategory::class);
    }


    /**
     * @return mixed
     */
    public function getTotalSubCategoryAttribute()
    {
        return $this->subCategory ? $this->subCategory()->count() : 0;
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateCategoryRequest;
use App\Http\Requests\UpdateCategoryRequest;
use App\Models\Category;
use App\Repositories\CategoryRepository;
use Exception;
use Flash;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\Redirector;

class CategoryController extends AppBaseController
{
    /** @var  CategoryRepository */
    private $categoryRepository;

    public function __construct(CategoryRepository $categoryRepo)
    {
        $this->categoryRepository = $categoryRepo;
    }

    /**
     * Display a listing of the Category.
     *
     * @param Request $request
     *
     * @return View
     */
    public function index(Request $request)
    {
        $categories = $this->categoryRepository->all();

        return view('categories.index',compact('categories'));
    }

    /**
     * Show the form for creating a new Category.
     *
     * @return View
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created Category in storage.
     *
     * @param CreateCategoryRequest $request
     *
     * @return View|RedirectResponse|Redirector
     */
    public function store(CreateCategoryRequest $request)
    {
        $input = $request->all();
        /** @var Category $category */
        $category = $this->categoryRepository->create($input);

        if ((isset($input['image']))) {
            $category->addMedia($input['image'])
                ->toMediaCollection(Category::IMG_PATH);
        }

        Flash::success('Category saved successfully.');

        return redirect(route('categories.index'));
    }

    /**
     * Display the specified Category.
     *
     * @param int $id
     *
     * @return View|RedirectResponse|Redirector
     */
    public function show($id)
    {
        $category = $this->categoryRepository->find($id);

        if (empty($category)) {
            Flash::error('Category not found');

            return redirect(route('categories.index'));
        }

        return view('categories.show')->with('category', $category);
    }

    /**
     * Show the form for editing the specified Category.
     *
     * @param int $id
     *
     * @return View|RedirectResponse|Redirector
     */
    public function edit($id)
    {
        $category = $this->categoryRepository->find($id);

        if (empty($category)) {
            Flash::error('Category not found');

            return redirect(route('categories.index'));
        }

        return view('categories.edit')->with('category', $category);
    }

    /**
     * Update the specified Category in storage.
     *
     * @param Category $category
     *
     * @param UpdateCategoryRequest $request
     *
     * @return View|RedirectResponse|Redirector
     */
    public function update(Category $category, UpdateCategoryRequest $request)
    {
        if (empty($category)) {
            Flash::error('Category not found');

            return redirect(route('categories.index'));
        }
        $input = $request->all();
        /* @Category $cate */
        $cate = $this->categoryRepository->update($input, $category->id);

        if ((isset($input['image']))) {
            $cate->clearMediaCollection(Category::IMG_PATH);
            $cate->addMedia($input['image'])
                ->toMediaCollection(Category::IMG_PATH);
        }

        Flash::success('Category updated successfully.');

        return redirect(route('categories.index'));
    }

    /**
     * Remove the specified Category from storage.
     *
     * @param int $id
     *
     * @throws Exception
     *
     * @return View|RedirectResponse|Redirector
     */
    public function destroy($id)
    {
        /** @var Category $category */
        $category = $this->categoryRepository->find($id);

        if (empty($category)) {
            Flash::error('Category not found');

            return redirect(route('categories.index'));
        }
        $category->clearMediaCollection(Category::IMG_PATH);
        $this->categoryRepository->delete($id);

        Flash::success('Category deleted successfully.');

        return redirect(route('categories.index'));
    }
}

resources/views/categories/create.blade.php
@extends('layouts.app')
@section('title')
    Create Category 
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h3 class="page__heading m-0">New Category</h3>
            <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                <a href="{{ route('categories.index') }}" class="btn btn-primary">Back</a>
            </div>
        </div>
        <div class="content">
            <div class="section-body">
               <div class="row">
                   <div class="col-lg-12">
                       <div class="card">
                           <div class="card-body ">
                                {!! Form::open(['route' => 'categories.store','files' => true]) !!}
                                    <div class="row">
                                        @include('categories.fields')
                                    </div>
                                {!! Form::close() !!}
                           </div>
                       </div>
                   </div>
               </div>
            </div>
        </div>
    </section>
@endsection
@push('scripts')
    <script src="{{ asset('js/jquery.uploadPreview.min.js') }}"></script>
    <script>
        $.uploadPreview({
            input_field: "#image-upload",   // Default: .image-upload
            preview_box: "#image-preview",  // Default: .image-preview
            label_field: "#image-label",    // Default: .image-label
            label_default: "Choose File",   // Default: Choose File
            label_selected: "Change File",  // Default: Change File
            no_label: false,                // Default: false
            success_callback: null          // Default: null
        });
    </script>
@endpush

resources/views/categories/edit.blade.php
@extends('layouts.app')
@section('title')
    Edit Category
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h3 class="page__heading m-0">Edit Category</h3>
            <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                <a href="{{ route('categories.index') }}" class="btn btn-primary">Back</a>
            </div>
        </div>
        <div class="content">
            <div class="section-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body ">
                                {!! Form::model($category, ['route' => ['categories.update', $category->id], 'method' => 'patch','files' => true]) !!}
                                <div class="row">
                                    @include('categories.fields')
                                </div>

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
@push('scripts')
    <script src="{{ asset('js/jquery.uploadPreview.min.js') }}"></script>
    <script>
        $.uploadPreview({
            input_field: '#image-upload',   // Default: .image-upload
            preview_box: '#image-preview',  // Default: .image-preview
            label_field: '#image-label',    // Default: .image-label
            label_default: 'Choose File',   // Default: Choose File
            label_selected: 'Change File',  // Default: Change File
            no_label: false,                // Default: false
            success_callback: true,          // Default: null
        });
    </script>
@endpush

resources/views/categories/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', old('name'), ['class' => 'form-control '. ($errors->has('name') ? 'is-invalid':'')]) !!}
    <div class="invalid-feedback">{{ $errors->first('name') }}</div>
</div>

<div class="form-group col-sm-6">
    <div id="image-preview" class="image-preview {{ $errors->has('image') ? 'border-danger' :''  }}" style="background-image: url('{{ isset($category) ? $category->image : '' }}')">
        <label for="image-upload" id="image-label">Choose File</label>
        <input type="file" name="image" id="image-upload">
    </div>
    <div class="text-danger">{{ $errors->first('image') }}</div>
</div>


<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('categories.index') }}" class="btn btn-light">Cancel</a>
</div>

resources/views/categories/index.blade.php
@extends('layouts.app')
@section('title')
    Categories
@endsection
@push('css')
    <link href="{{ asset('assets/css/jquery.dataTables.min.css') }}" rel="stylesheet" type="text/css"/>
@endpush
@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Categories</h1>
            <div class="section-header-breadcrumb">
                <a href="{{ route('categories.create')}}" class="btn btn-primary form-btn"> <i
                            class="fas fa-plus" style="font-size: 10px"></i> Category </a>
            </div>
        </div>
        <div class="section-body">
            @include('flash::message')
            <div class="card">
                <div class="card-body">
                    @include('categories.table')
                </div>
            </div>
        </div>
    </section>
@endsection
@push('scripts')
    <script src="{{ asset('assets/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ mix('assets/js/custom/custom-datatable.js') }}"></script>
    <script>
        $('#categories-table').DataTable();
    </script>
@endpush

resources/views/categories/show.blade.php
@extends('layouts.app')
@section('title')
    Category Details 
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Category Details</h1>
            <div class="section-header-breadcrumb">
                <a href="{{ route('categories.index') }}"
                     class="btn btn-primary form-btn float-right">Back</a>
            </div>
        </div>
        <div class="section-body">
           <div class="card">
                <div class="card-body">
                        <div class="row">
                            @include('categories.show_fields')
                        </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/categories/show_fields.blade.php
<!-- Name Field -->
<div class="form-group col-md-6">
    {!! Form::label('name', 'Name:',['class' => 'font-weight-bold']) !!}
    <p>{{ $category->name }}</p>
</div>


<!-- Created At Field -->
<div class="form-group col-md-6">
    {!! Form::label('created_at', 'Created At:',['class' => 'font-weight-bold']) !!}
    <p>{{ $category->created_at }}</p>
</div>


<!-- Updated At Field -->
<div class="form-group col-md-6">
    {!! Form::label('updated_at', 'Updated At:',['class' => 'font-weight-bold']) !!}
    <p>{{ $category->updated_at }}</p>
</div>

<!-- Image Field -->
<div class="form-group col-md-12">
    {!! Form::label('id', 'Image:',['class' => 'font-weight-bold']) !!}
    <img src="{{ $category->image }}" />
</div>

resources/views/categories/table.blade.php
<div class="table-responsive-sm">
    <table class="table table-striped table-bordered" id="categories-table">
        <thead>
        <tr>
            <th>Name</th>
            <th>Image</th>
            <th class="action-column" style="width: 15%">Total Sub Categories</th>
            <th class="action-column">Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($categories as $category)
            <tr>
                <td>{{ $category->name }}</td>
                <td><img class="table-img" src="{{ $category->image }}" alt="no image"></td>
                <td class="text-center"><a href="{{ route('subCategories.index') }}" class="badge badge-primary">{{ $category->total_sub_category }}</a> </td>
                <td class="text-center">
                    {!! Form::open(['route' => ['categories.destroy', $category->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('categories.show', [$category->id]) !!}" class='btn btn-light action-btn '><i
                                    class="fa fa-eye"></i></a>
                        <a href="{!! route('categories.edit', [$category->id]) !!}"
                           class='btn btn-warning action-btn edit-btn'><i class="fa fa-edit"></i></a>
                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger action-btn delete-btn', 'onclick' => 'return confirm("Are you sure want to delete this record ?")']) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>