routes/web.php
<?php

use App\Http\Controllers\FrontSettingController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\SettingController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::post('/register',[HomeController::class,'register'])->name('register');

// Home
Route::get('/', [HomeController::class, 'home'])->name('home');
// Men
Route::get('/men', [HomeController::class, 'men'])->name('new_arrivals');
Route::get('/women', [HomeController::class, 'woMen'])->name('women_arrivals');
Route::get('/accessories', [HomeController::class, 'Accessories'])->name('accessories_arrivals');
Route::get('product/{id}/details', [HomeController::class, 'menDetails'])->name('men.details');
Route::get('page/contact-us', [HomeController::class, 'contactUs'])->name('page.contact-us');
Route::get('page/return-exchange', [HomeController::class, 'returnExchange'])->name('page.return-exchange');
Route::get('page/privacy-policy', [HomeController::class, 'privacyPolicy'])->name('page.privacy-policy');
Route::get('page/return-policy', [HomeController::class, 'returnPolicy'])->name('page.return-policy');
Route::get('page/offer-policy', [HomeController::class, 'offerPolicy'])->name('page.offer-policy');
//Route::get('women/{id}/details',[HomeController::class,'womenDetails'])->name('women.details');
//Route::get('men/details',function (){
//    return view('by_pass.men_details');
//})->name('men_details');


Route::get('/welcome', function () {
    return view('web.welcome');
});
Route::get('/mens', function () {
    return view('web.mens');
})->name('mens');
Route::get('/single', function () {
    return view('web.single');
})->name('single');
Route::get('/contact', function () {
    return view('web.contact');
})->name('contact');

//Route::middleware(['auth:sanctum', 'verified','role:Admin'])->get('/dashboard', function () {
//    return view('dashboard.dashboard');
//})->name('dashboard');

//Route::group(['middleware' => ['auth:sanctum', 'verified','role:Admin']],function (){
    Route::get('dashboard', [HomeController::class, 'dashboard'])->name('dashboard');
//});


Route::group(['middleware' => 'auth'], function () {

    Route::get('mySetting', [HomeController::class, 'mySetting'])->name('mySetting');

});


// settings routes
Route::get('settings', [SettingController::class, 'index'])->name('settings.index');
Route::post('settings', [SettingController::class, 'update'])->name('settings.update');

// front settings
Route::get('setting/home', [FrontSettingController::class, 'home'])->name('front.settings.home');
Route::post('setting/home', [FrontSettingController::class, 'homeUpdate'])->name('front.settings.home.update');
Route::delete('delete-home-slider/{homeImageSlider}', [FrontSettingController::class, 'deleteHomeSlider'])->name('front.settings.deleteHomeSlider');

Route::get('setting/contact-us', [FrontSettingController::class, 'contactUs'])->name('front.settings.contactUs');
Route::post('setting/contact-us',
    [FrontSettingController::class, 'contactUsUpdate'])->name('front.settings.contactUs.update');

// Order
Route::get('orders', [OrderController::class, 'index'])->name('orders.index');
Route::post('placeOrder', [OrderController::class, 'placeOrder'])->name('placeOrder');
Route::get('getOrderDetails', [OrderController::class, 'getOrderDetails'])->name('getOrderDetails');
Route::post('getOrderDetails', [OrderController::class, 'storeOrderDetails'])->name('storeOrderDetails');
Route::post('storeOrderNewAddress', [OrderController::class, 'storeOrderNewAddress'])->name('storeOrderNewAddress');
Route::post('chooseAddress', [OrderController::class, 'chooseAddress'])->name('chooseAddress');
Route::get('removeProductToBag', [OrderController::class, 'removeProductToBag'])->name('removeProductToBag');


Route::resource('categories', App\Http\Controllers\CategoryController::class);
Route::resource('subCategories', App\Http\Controllers\SubCategoryController::class);
Route::get('get-sub-categories',
    [App\Http\Controllers\SubCategoryController::class, 'getSubCategory'])->name('get.sub.categories');
Route::resource('products', App\Http\Controllers\ProductController::class);
Route::post('products/change-is-active',
    [App\Http\Controllers\ProductController::class, 'changeIsActive'])->name('products.change-is-active');
Route::get('productColorDelete',
    [App\Http\Controllers\ProductController::class, 'productColorDelete'])->name('productColorDelete');
Route::get('productColorImageDelete',
    [App\Http\Controllers\ProductController::class, 'productColorImageDelete'])->name('productColorImageDelete');

Route::resource('colors', App\Http\Controllers\ColorController::class);
Route::resource('variants', App\Http\Controllers\VariantController::class);


Route::group(['prefix' => 'crud-gui'], function () {
    Route::get('generator_builder',
        '\Crud\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');

    Route::get('field_template',
        '\Crud\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');

    Route::get('relation_field_template',
        '\Crud\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');

    Route::post('generator_builder/generate',
        '\Crud\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');

    Route::post('generator_builder/rollback',
        '\Crud\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');

    Route::post(
        'generator_builder/generate-from-file',
        '\Crud\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
    )->name('io_generator_builder_generate_from_file');
});

app/Models/ProductColor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;


class ProductColor extends Model implements HasMedia
{
    use HasMediaTrait;

    public $table = 'product_colors';

    const IMG_PATH = 'product_colors';

    public $fillable = [
        'product_id',
        'color',
    ];

    /**
     * @return string
     */
    public function getImageAttribute()
    {
        /** @var Media $media */
        $media = $this->getMedia(self::IMG_PATH)->first();
        if (! empty($media)) {
            return $media->getFullUrl();
        }

        return 'http://webyzona.com/templates/themeforest/royal-market/images/product-7.jpg';
    }

    /**
     * @return string
     */
    public function getAllImageAttribute()
    {
        return $this->getMedia(self::IMG_PATH)->all();
    }

    /**
     * @return BelongsTo
     */
    public function product()
    {
        return $this->belongsTo(Product::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateProductRequest;
use App\Http\Requests\UpdateProductRequest;
use App\Models\Category;
use App\Models\Color;
use App\Models\Product;
use App\Models\ProductColor;
use App\Models\ProductVariant;
use App\Models\Setting;
use App\Models\SubCategory;
use App\Models\Variant;
use App\Repositories\ProductRepository;
use Flash;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\Redirector;
use Response;
use Spatie\MediaLibrary\Models\Media;

class ProductController extends AppBaseController
{
    /** @var  ProductRepository $productRepo */
    private $productRepository;

    public function __construct(ProductRepository $productRepo)
    {
        $this->productRepository = $productRepo;
    }

    /**
     * Display a listing of the Product.
     *
     * @param  Request  $request
     *
     * @return View
     */
    public function index(Request $request)
    {
        $products = Product::with(['category', 'subCategory'])->get();

        return view('products.index')
            ->with('products', $products);
    }

    /**
     * Show the form for creating a new Product.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        /** @var Category $categories */
        $categories = Category::whereHas('subCategory')->pluck('name', 'id');
        $colors = Color::all();
        $variants = Variant::all();
        $settings = Setting::pluck('value','key')->toArray();

        return view('products.create',compact('categories','colors','variants','settings'));
    }

    /**
     * Store a newly created Product in storage.
     *
     * @param  CreateProductRequest  $request
     *
     * @return Redirector
     */
    public function store(CreateProductRequest $request)
    {
        $input = $request->all();

        /** @var Product $product */
        $product = $this->productRepository->create($input);
        if(isset($input['variants']) && $input['variants']){
            foreach ($input['variants'] as $index => $variant) {
                ProductVariant::create([
                    'name' => $variant,
                    'product_id' => $product->id,
                ]);
            }
        }

        if(isset($input['colors']) && $input['colors']){
            foreach ($input['colors'] as $index => $color) {
                $productColor = ProductColor::create([
                    'color' => $color,
                    'product_id' => $product->id,
                ]);
                if(isset($input['colors-img']) && $input['colors-img']){
                    foreach ($input['colors-img'][$color] as $image){
                        $productColor->addMedia($image)
                            ->toMediaCollection(ProductColor::IMG_PATH);
                    };
                }
            }
        }

        if ((isset($input['image']))) {
            $product->addMedia($input['image'])
                ->toMediaCollection(Product::IMG_PATH);
        }

        Flash::success('Product saved successfully.');

        return redirect(route('products.index'));
    }

    /**
     * Display the specified Product.
     *
     * @param  int  $id
     *
     * @return RedirectResponse|Redirector|Response
     */
    public function show($id)
    {
        $product = $this->productRepository->find($id);

        if (empty($product)) {
            Flash::error('Product not found');

            return redirect(route('products.index'));
        }

        return view('products.show')->with('product', $product);
    }

    /**
     * Show the form for editing the specified Product.
     *
     * @param  int  $id
     *
     * @return Application|RedirectResponse|Redirector|Response
     */
    public function edit($id)
    {
        $data['product'] = $this->productRepository->find($id);
        $data['colors'] = Color::all();
        $data['variants'] = Variant::all();
        $data['settings'] = Setting::pluck('value','key')->toArray();

        if (empty($data['product'])) {
            Flash::error('Product not found');

            return redirect(route('products.index'));
        }

        $data['categories'] = Category::pluck('name', 'id');
        $data['subCategories'] = SubCategory::pluck('name', 'id');

        return view('products.edit')->with($data);
    }

    /**
     * Update the specified Product in storage.
     *
     * @param  Product  $product
     *
     * @param  UpdateProductRequest  $request
     *
     * @return Application|RedirectResponse|Redirector|Response
     */
    public function update(Product $product, UpdateProductRequest $request)
    {
        if (empty($product)) {
            Flash::error('Product not found');

            return redirect(route('products.index'));
        }
        $input = $request->all();
        /** @var Product $prod */
        $prod = $this->productRepository->update($input, $product->id);
        if(isset($input['variants']) && $input['variants']){
            foreach ($input['variants'] as $index => $variant) {
                ProductVariant::create([
                    'name' => $variant,
                    'product_id' => $product->id,
                ]);
            }
        }
        if(isset($input['colors']) && $input['colors']){
            foreach ($input['colors'] as $index => $color) {
                $productColor = ProductColor::create([
                    'color' => $color,
                    'product_id' => $product->id,
                ]);
                $productColor->addMedia($input['colors-img-'.$color])
                    ->toMediaCollection(ProductColor::IMG_PATH);
            }
        }
        if ((isset($input['image']))) {
            $product->clearMediaCollection(Product::IMG_PATH);
            $product->addMedia($input['image'])
                ->toMediaCollection(Product::IMG_PATH);
        }

        Flash::success('Product updated successfully.');

        return redirect(route('products.index'));
    }

    /**
     * Remove the specified Product from storage.
     *
     * @param  int  $id
     *
     * @throws \Exception
     *
     * @return Application|RedirectResponse|Redirector|Response
     */
    public function destroy($id)
    {
        /** @var Product $product */
        $product = $this->productRepository->find($id);

        if (empty($product)) {
            Flash::error('Product not found');

            return redirect(route('products.index'));
        }
        $product->colors()->delete();
        $product->variants()->delete();
        $product->clearMediaCollection(Product::IMG_PATH);
        $this->productRepository->delete($id);

        Flash::success('Product deleted successfully.');

        return redirect(route('products.index'));
    }

    /**
     * @param Request $request
     * @return mixed
     */
    public function changeIsActive(Request $request)
    {
        /** @var Setting $setting */
        $setting = Setting::where('key', 'product_is_active')->first();
        $setting->update(['value' => !$setting->value]);

        return $this->sendsuccess('Status changed successfully.');
    }

    /**
     * @param Request $request
     *
     * @return mixed
     */
    public function productColorDelete(Request $request)
    {
        $input = $request->all();
        $productColor = ProductColor::find($input['id']);
        $productColor->clearMediaCollection(ProductColor::IMG_PATH);
        $productColor->delete();

        return $this->sendSuccess('Product Color Remove SuccessFully');
    }

    /**
     * @param Request $request
     *
     * @return mixed
     */
    public function productColorImageDelete(Request $request)
    {
        $input = $request->all();
        $productColorImage = Media::find($input['id']);
        $productColorImage->delete();

        return $this->sendSuccess('Product Color Image Remove SuccessFully');
    }
}

resources/views/products/create.blade.php
@extends('layouts.app')
@section('title')
    Create Product
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h3 class="page__heading m-0">New Product</h3>
            <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                <a href="{{ route('products.index') }}" class="btn btn-primary">Back</a>
            </div>
        </div>
        <div class="content">
            <div class="section-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body ">
                                {!! Form::open(['route' => 'products.store','files' => true]) !!}
                                <div class="row">
                                    @include('products.fields')
                                </div>
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
@push('scripts')
    <script src="{{ asset('js/jquery.uploadPreview.min.js') }}"></script>
    <script>
        let getSubCategoriesURL = '{{ route('get.sub.categories') }}';
        let oldSubCategory = '{{ old('sub_category_id') }}';

        $('.searchIsActive').on('change', function () {
            if($(this).prop("checked") == true){
                $('.productImageDiv').addClass('d-none');
            }else{
                $('.productImageDiv').removeClass('d-none');
            }
            $.ajax({
                url: '/products/change-is-active',
                method: 'post',
                data: $('#searchIsActive').serialize(),
                dataType: 'JSON',
                success: function (result) {
                    if (result.success) {
                        displaySuccessMessage(result.message);

                    }
                },
                error: function (result) {
                    displayErrorMessage(result.responseJSON.message);
                },
            });
        });
    </script>
    <script src="{{ mix('assets/js/ticket/create-edit.js') }}"></script>
@endpush

resources/views/products/edit.blade.php
@extends('layouts.app')
@section('title')
    Edit Product
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h3 class="page__heading m-0">Edit Product</h3>
            <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                <a href="{{ route('products.index') }}" class="btn btn-primary">Back</a>
            </div>
        </div>
        <div class="content">
            <div class="section-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body ">
                                {!! Form::model($product, ['route' => ['products.update', $product->id], 'method' => 'patch','files' => true]) !!}
                                <div class="row">
                                    @include('products.fields')
                                </div>

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
@push('scripts')
    <script src="{{ asset('js/jquery.uploadPreview.min.js') }}"></script>
    <script>
        let productColorDelete = "{{ route('productColorDelete') }}";
        let productColorImageDelete = "{{ route('productColorImageDelete') }}";

        $.uploadPreview({
            input_field: '#image-upload',   // Default: .image-upload
            preview_box: '#image-preview',  // Default: .image-preview
            label_field: '#image-label',    // Default: .image-label
            label_default: 'Choose File',   // Default: Choose File
            label_selected: 'Change File',  // Default: Change File
            no_label: false,                // Default: false
            success_callback: null,          // Default: null
        });
        let getSubCategoriesURL = '{{ route('get.sub.categories') }}';
        let oldSubCategory = '{{ old('sub_category_id') ?? $product->sub_category_id }}';

        $('.searchIsActive').on('change', function () {
            $.ajax({
                url: '/products/change-is-active',
                method: 'post',
                data: $('#searchIsActive').serialize(),
                dataType: 'JSON',
                success: function (result) {
                    if (result.success) {
                        displaySuccessMessage(result.message);
                        location.reload();
                    }
                },
                error: function (result) {
                    displayErrorMessage(result.responseJSON.message);
                },
            });
        });

        $('.productColorDelete').on('click',function (){
            let productColorId = $(this).attr('data-id');
            $.ajax({
                url : productColorDelete,
                data : {id:productColorId},
                methods:'GET',
                success: function (result) {
                    if (result.success) {
                        displaySuccessMessage(result.message);
                        location.reload();
                    }
                },
                error: function (result) {
                    displayErrorMessage(result.responseJSON.message);
                },
            });
        });

        $('.productColorImageDelete').on('click',function (){
            let productImageId = $(this).attr('data-id');
            $.ajax({
                url : productColorImageDelete,
                data : {id:productImageId},
                methods:'GET',
                success: function (result) {
                    if (result.success) {
                        displaySuccessMessage(result.message);
                        location.reload();
                    }
                },
                error: function (result) {
                    displayErrorMessage(result.responseJSON.message);
                },
            });
        });
    </script>
    <script src="{{ mix('assets/js/ticket/create-edit.js') }}"></script>
@endpush

resources/views/products/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}<span class="text-danger">*</span>
    {!! Form::text('name', old('name'), ['class' => 'form-control '. ($errors->has('name') ? 'is-invalid':''),'required']) !!}
    <div class="invalid-feedback">{{ $errors->first('name') }}</div>
</div>

<!-- Seller Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('seller_name', 'Seller Name:') !!}
    {!! Form::text('seller_name', old('seller_name'), ['class' => 'form-control '. ($errors->has('seller_name') ? 'is-invalid':'')]) !!}
    <div class="invalid-feedback">{{ $errors->first('seller_name') }}</div>
</div>

<!-- Category Field -->
<div class="form-group col-sm-6">
    {!! Form::label('category_id', 'Category:') !!}<span class="text-danger">*</span>
    {!! Form::select('category_id', $categories, (isset($product)) ? $product->category_id : $categories->keys()->first(), ['class' => 'form-control select2 '. ($errors->has('category_id') ? 'is-invalid':'') ,'id' => 'category','required']) !!}
    <div class="invalid-feedback">{{ $errors->first('category_id') }}</div>
</div>

<!-- Sub Category Field -->
<div class="form-group col-sm-6">
    {!! Form::label('sub_category_id', 'Sub Category:') !!}<span class="text-danger">*</span>
    {!! Form::select('sub_category_id', [], null, ['class' => 'form-control select2 '. ($errors->has('sub_category_id') ? 'is-invalid':''),'id' => 'subCategory','required']) !!}
    <div class="invalid-feedback">{{ $errors->first('sub_category_id') }}</div>
</div>


<!-- Status Field -->
<div class="form-group col-sm-6">
    {!! Form::label('status', 'Status:') !!}<span class="text-danger">*</span>
    {!! Form::select('status', \App\Models\Product::STATUS, null, ['class' => 'form-control select2 '. ($errors->has('status') ? 'is-invalid':''),'required']) !!}
    <div class="invalid-feedback">{{ $errors->first('status') }}</div>
</div>


<!-- Price Field -->
<div class="form-group col-sm-6">
    {!! Form::label('price', 'Price:') !!}<span class="text-danger">*</span>
    {!! Form::number('price', null, ['class' => 'form-control '. ($errors->has('price') ? 'is-invalid':''),'required']) !!}
    <div class="invalid-feedback">{{ $errors->first('price') }}</div>
</div>


<!-- Description Field -->
<div class="form-group col-sm-12">
    {!! Form::label('description', 'Description:') !!}
    {!! Form::textarea('description', old('description'), ['class' => 'form-control '. ($errors->has('description') ? 'is-invalid':'')]) !!}
    <div class="invalid-feedback">{{ $errors->first('description') }}</div>
</div>
@if(isset($product))
    <div class="form-group col-sm-12">
        <label class="form-label">Colors :</label>
        @foreach($product->colors as $color)
            <div class="row mb-3 gutters-xs">
                <div class="col-auto d-flex flex-column align-items-center justify-content-center">
                    <label class="colorinput">
                        <span class="colorinput-color " style="background-color: {{ $color->color }}"></span>

                    </label>
                    <button class="btn btn-sm btn-outline-danger productColorDelete mb-2" data-id="{{ $color->id }}" style="width: 100px">Remove Color</button>
                    <button class="btn btn-sm btn-outline-success mt-2" style="width: 100px">Add Image</button>
                </div>
                <div class="col-10 ml-3">
                    <div class="d-flex align-items-center ">
                        @foreach($color->all_image as $image)
                            <img src="{{ $image->getFullUrl() }}" alt="" class=" mb-2 ml-2" width="80" height="80">
                            <button type="button"  class="ml-2 mb-2 btn-icon-round  btn btn-sm btn-outline-danger productColorImageDelete" data-id="{{ $image->id }}"><i class="fa fa-times-circle"></i></button>
                        @endforeach
                    </div>
                </div>
            </div>
        @endforeach
    </div>
@else
    <div class="form-group col-sm-12">
        <label class="form-label">Colors :</label>
        @foreach($colors as $color)
            <div class="row gutters-xs">
                <div class="col-auto">
                    <label class="colorinput">
                        <input name="colors[]" type="checkbox" value="{{ $color->name }}" class="colorinput-input chk-color">
                        <span class="colorinput-color " style="background-color: {{ $color->name }}"></span>
                    </label>
                </div>
                <div class="col-auto color-image d-none">
                    <div class="d-flex">
                        <div class="col-12 mb-3 align-items-center colo-input-main">
                            <div class="d-flex color-input-div align-items-center mb-3">
                                <input type="file" name="colors-img[{{ $color->name }}][]" class="form-control color-img-input">
                            </div>
                        </div>
                        <button type="button" class="btn-icon-round mt-2 btn btn-sm btn-outline-success btn-add-file">
                            <i class="fa fa-plus-circle"></i></button>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
@endif

<div class="form-group col-sm-6">
    <label class="form-label">Variants :</label>
    <div class="selectgroup selectgroup-pills">
        @foreach($variants as $variant)
            <label class="selectgroup-item">
                <input type="checkbox" name="variants[]" value="{{ $variant->name  }}" class="selectgroup-input">
                <span class="selectgroup-button">{{ $variant->name }}</span>
            </label>
        @endforeach
    </div>
</div>

{{--<div class="form-group col-sm-6">--}}
{{--    <form method="post" id="searchIsActive">--}}
{{--        @csrf--}}
{{--        <div class="form-group mb-1">--}}
{{--            <label class="custom-switch switch-label row">--}}
{{--                <input type="checkbox" name="product_is_active" class="custom-switch-input searchIsActive" {{ ($settings['product_is_active'] == 1) ? 'checked' : '' }} >--}}
{{--                <span class="custom-switch-indicator switch-span"></span>--}}
{{--            </label>--}}
{{--        </div>--}}
{{--    </form>--}}
{{--</div>--}}

{{--@if($settings['product_is_active'] == 0)--}}
    <!-- Image Field -->
    <div class="form-group col-sm-12 productImageDiv">
        <div id="image-preview" class="image-preview {{ $errors->has('image') ? 'border-danger' :''  }}" style="background-image: url('{{ isset($product) ? $product->image : '' }}')">
            <label for="image-upload" id="image-label">Choose File</label>
            <input type="file" name="image" id="image-upload" {{ isset($product) ? '' : 'required' }} >
        </div>
        <div class="text-danger">{{ $errors->first('image') }}</div>
    </div>
{{--@endif--}}

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('products.index') }}" class="btn btn-light">Cancel</a>
</div>

resources/views/products/index.blade.php
@extends('layouts.app')
@section('title')
    Products
@endsection
@push('css')
    @livewireStyles
@endpush
@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Products</h1>
            <div class="section-header-breadcrumb">
                <a href="{{ route('products.create')}}" class="btn btn-primary form-btn"><i
                            class="fas fa-plus" style="font-size: 10px;"></i> Product</a>
            </div>
        </div>
        <div class="section-body">
            @livewire('show-products')
        </div>
    </section>
@endsection
@push('scripts')
    @livewireScripts
    <script type="text/javascript" src="{{ asset('web/js/pignose.layerslider.js') }}"></script>
    <script>
        $(document).on('click','.chk-color',function (){
            if($(this).is(":checked")) {
                $(this).parents().parent().parent().prevAll().find('.product-card__image').attr('src',$(this).next().next().val());
            }
        });
    </script>
@endpush

resources/views/products/show.blade.php
@extends('layouts.app')
@section('title')
    Product Details
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Product Details</h1>
            <div class="section-header-breadcrumb">
                <a href="{{ route('products.index') }}"
                   class="btn btn-primary form-btn float-right">Back</a>
            </div>
        </div>
        <div class="section-body">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        @include('products.show_fields')
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection